CREATE DATABASE ayush_eduvibe;
USE ayush_eduvibe;
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),email VARCHAR(100),phone VARCHAR(20),password VARCHAR(255));
CREATE TABLE enquiries(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),email VARCHAR(100),phone VARCHAR(20),country VARCHAR(100),message TEXT);
CREATE TABLE contacts(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),email VARCHAR(100),subject VARCHAR(150),message TEXT);
CREATE TABLE admin(id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50),password VARCHAR(255));
INSERT INTO admin(username,password) VALUES('admin','admin123');